### PR TITLE
Requested changes for switch-exhaustiveness-check

### PR DESCRIPTION
**Pull request by cust0dian-old**

### CODE REVIEW

**Comment by cust0dian-old** [comment]
Sorry for the noise changes from the merge of `master` — I wanted to make it easier to get upstream PR into a mergeable state. You can double-check my additions if you [compare my fork to upstream master](https://github.com/typescript-eslint/typescript-eslint/compare/master...cust0dian:switch-exhaustiveness-check).

**Comment by drets** [comment]
@cust0dian I haven't read the PR super carefully, just surfed it, all looks good to me. Is it ready for merge from your perspective or you want to add something else? If it's ready, I'll just merge it straight away, thank you.

**Comment by cust0dian-old** [comment]
@drets yeah, I think it's ready to be merged! Thanks!

Also, if you wish, you can [add me as a collaborator for this repo](https://github.com/drets/typescript-eslint/settings/access) so if there are any comments from the upstream review I can push changes directly here and free you from any work that might arise.

**Comment by drets** [comment]
@cust0dian I wish :relaxed:

**Pull request merged**
